version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - frontend
      - backend
    ports:
      - "897:80"
    container_name: apachephp_dirty_secret

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    volumes:
            - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_dirty_secret


networks:
  frontend:
  backend:
volumes:
    data:
